env:
  es6: true
  browser: true
  commonjs: true

extends:
  [
    "plugin:react/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "prettier",
    "plugin:prettier/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
  ]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ["react", "simple-import-sort", "prettier"]

settings:
  react:
    version: "17"

rules:
  {
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    "prettier/prettier": "error",
    "no-unused-vars": "error",
    "import/extensions": ["error", "never"],
    "import/no-unresolved": [
      2, 
      { "caseSensitive": false }
  }
