require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'vendor/bundle/**/*'
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Max: 50

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: space
