version: '3.0'
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}

  webpacker:
    image: ${DOCKER_IMAGE_NAME-melobeem}
    ports:
      - 3035:3035

  web:
    image: ${DOCKER_IMAGE_NAME-melobeem}
    build:
      context: .
      args:
        precompileassets: 'not'
    links:
      - db
      - webpacker
    ports:
      - 3000:3000
    environment:
      PG_PASSWORD: ${DB_USER_PASSWORD}
