default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: melobeem-github-actions
  pool: 5
  username: postgres
  password: postgres
test:
  <<: *default
development:
  <<: *default
