env:
  RUBY_VERSION: 2.7.x

name: Run Tests & Linters
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Gems
        id: gem-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Cache Assets
        id: assets-cache
        uses: actions/cache@v1
        with:
          path: public/packs-test
          key: ${{ runner.os }}-assets-${{ steps.extract_branch.outputs.branch }}
          restore-keys: |
            ${{ runner.os }}-assets-

      - name: Install dependencies
        run: |
          gem install bundler
          bundler config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Yarn Install
        run: bin/rails yarn:install

      - name: Compile Assets
        shell: bash
        run: |
          if [[ ! -d public/packs-test ]]; then
            bundle exec rails webpacker:compile
          else
            echo "No need to compile assets."
          fi

      - name: Setup DB
        run: bin/rails db:drop db:create db:structure:load --trace

      - name: Run tests
        run: bundler exec rspec

      - name: Zeitwerk Check
        run: bundle exec rails zeitwerk:check

      - name: StandardRB Check
        run: bundle exec standardrb --format progress

      - name: Prettier-Standard Check
        run: yarn run --ignore-engines prettier-standard --check 'app/**/*.js'
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: coverage-report
          path: coverage
